language: python            # this works for Linux but is an error on macOS or Windows

jobs:
  include:
    - name: "Python 3.7.4 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
    
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew update
        - brew install gcc
    
install:
  - pip3 install --upgrade pip
  - pip3 install .

script:
  - pytest

